import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProviderForNextAuth from "@/nextAuth/SessionProviderForNextAuth";
import ReduxStoreProvider from "@/redux/ReduxStoreProvider";
import MyContextProvider from "@/lib/MyContextProvider";
import { Toaster } from "react-hot-toast";
import CurrencyInitializer from "@/components/CurrencyInitializer";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sellapy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* ✅ Google Tag Manager */}
        <Script id="google-tag-manager" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-TTF4FGRH');
          `}
        </Script>

        {/* ✅ Google Analytics GA4 */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-4EWXXL78BW"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-4EWXXL78BW');
          `}
        </Script>
      </head>

      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ GTM noscript - must be first inside body */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-TTF4FGRH"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>

        <MyContextProvider>
          <SessionProviderForNextAuth>
            <ReduxStoreProvider>
              <CurrencyInitializer />
              {children}

              {/* ✅ Omnisend (your existing script - kept) */}
              <Script id="omnisend" strategy="afterInteractive">
                {`
                  window.omnisend = window.omnisend || [];
                  omnisend.push(["brandID", "6984d61ff7714ebd25ccdb7d"]);
                  omnisend.push(["track", "$pageViewed"]);
                  !function(){var e=document.createElement("script");
                  e.type="text/javascript",e.async=!0,
                  e.src="https://omnisnippet1.com/inshop/launcher-v2.js";
                  var t=document.getElementsByTagName("script")[0];
                  t.parentNode.insertBefore(e,t)}();
                `}
              </Script>
            </ReduxStoreProvider>

            <Toaster
              position="top-right"
              toastOptions={{
                duration: 4000,
                style: {
                  background: "#363636",
                  color: "#fff",
                },
              }}
            />
          </SessionProviderForNextAuth>
        </MyContextProvider>
      </body>
    </html>
  );
}